### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by uioficial** [lsadle/console-command-runner#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: [console-command-runner](https://github.com/lsadle/console-command-runner) package 1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At C:\Users\theiv_000\.atom\packages\console-command-runner\lib\console-command-runner.js:56

TypeError: Cannot read property 'path' of undefined
    at Object.run (/packages/console-command-runner/lib/console-command-runner.js:56:60)
    at HTMLElement.consoleCommandRunnerRun (/packages/console-command-runner/lib/console-command-runner.js:34:48)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:350034)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:1231386)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:1227520)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:285213)
```

### Commands

```
 21x -0:30.9.0 console-command-runner:run (input.hidden-input)
     -0:02.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
console-command-runner 1.1.0 
midnight-owl-syntax 0.1.0 
teletype 0.13.3 
```

**Comment by uioficial** [comment]
waserdjghbgvgbnm

**Comment by lsadle** [comment]
What are the steps to reproduce and did you have a project open at the time?

**Comment by lsadle** [comment]
The only way I can reproduce the issue is to not have a project open (and therefore not have a path to open Command Prompt with).  If the issue persists with a project open.  Please attach the steps to reproduce the problem and the console logs which can be found under the Atom menu View -> Developer -> Toggle Developer Tools -> {Developer tools opens} -> Console

![image](https://user-images.githubusercontent.com/11892833/50364831-5772eb00-0537-11e9-8cde-ccd0d9d36b26.png)
