### ISSUE TITLE
Uncaught TypeError: Cannot read property 'f5Command' of undefined

### ISSUE THREAD

**Issue by Shyam2048** [lsadle/console-command-runner#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [console-command-runner](https://github.com/lsadle/console-command-runner) package 1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'f5Command' of undefined

```
At C:\Users\sahil\.atom\packages\console-command-runner\lib\console-command-runner.js:57

TypeError: Cannot read property 'f5Command' of undefined
    at Object.run (/packages/console-command-runner/lib/console-command-runner.js:57:70)
    at HTMLElement.consoleCommandRunnerRun (/packages/console-command-runner/lib/console-command-runner.js:34:48)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:350017)
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:677438)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:840539)
    at SelectListView.didClickItem (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:838481)
    at ListItemView.onclick (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:839513)
    at ListItemView.didClick (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:841559)
```

### Commands

```
  3x -2:07.8.0 command-palette:toggle (input.hidden-input)
  3x -1:34.8.0 console-command-runner:run (input.hidden-input)
     -1:07.1.0 command-palette:toggle (input.hidden-input)
     -0:54.8.0 console-command-runner:toggle (input.hidden-input)
     -0:45.1.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:25.6.0 command-palette:toggle (input.hidden-input)
     -0:15 console-command-runner:run (input.hidden-input)
```

### Non-Core Packages

```
console-command-runner 1.1.0 
```

**Comment by nishadmehendale** [comment]
Same issue reported

**Comment by masademan** [comment]
same here

**Comment by George-Kariuki** [comment]
how do we solve it?
